# CMake generated Testfile for 
# Source directory: /home/daniel/Projects/vesper/tests
# Build directory: /home/daniel/Projects/vesper/build-cpu/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CoreEnumTests "/home/daniel/Projects/vesper/build-cpu/tests/core_tests")
set_tests_properties(CoreEnumTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;4;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(DTypeTests "/home/daniel/Projects/vesper/build-cpu/tests/dtype_tests")
set_tests_properties(DTypeTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;9;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(DeviceTests "/home/daniel/Projects/vesper/build-cpu/tests/device_tests")
set_tests_properties(DeviceTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;14;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(StorageTests "/home/daniel/Projects/vesper/build-cpu/tests/storage_tests")
set_tests_properties(StorageTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;19;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(StorageGranularTests "/home/daniel/Projects/vesper/build-cpu/tests/storage_granular_tests")
set_tests_properties(StorageGranularTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;24;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TensorTests "/home/daniel/Projects/vesper/build-cpu/tests/tensor_tests")
set_tests_properties(TensorTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;29;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TensorGranularTests "/home/daniel/Projects/vesper/build-cpu/tests/tensor_granular_tests")
set_tests_properties(TensorGranularTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;34;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(ZerosTests "/home/daniel/Projects/vesper/build-cpu/tests/zeros_tests")
set_tests_properties(ZerosTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;39;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TensorPropsTests "/home/daniel/Projects/vesper/build-cpu/tests/tensor_props_tests")
set_tests_properties(TensorPropsTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;44;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(StorageAdvancedTests "/home/daniel/Projects/vesper/build-cpu/tests/storage_advanced_tests")
set_tests_properties(StorageAdvancedTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;49;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(ElementwiseOpTests "/home/daniel/Projects/vesper/build-cpu/tests/elementwise_op_tests")
set_tests_properties(ElementwiseOpTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;54;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(GemmKernelTests "/home/daniel/Projects/vesper/build-cpu/tests/gemm_kernel_tests")
set_tests_properties(GemmKernelTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;59;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(MatmulOpTests "/home/daniel/Projects/vesper/build-cpu/tests/matmul_op_tests")
set_tests_properties(MatmulOpTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;64;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(GemmComprehensiveTests "/home/daniel/Projects/vesper/build-cpu/tests/gemm_comprehensive_tests")
set_tests_properties(GemmComprehensiveTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;69;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(ReductionOpTests "/home/daniel/Projects/vesper/build-cpu/tests/reduction_op_tests")
set_tests_properties(ReductionOpTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;74;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(BackendConsistencyTests "/home/daniel/Projects/vesper/build-cpu/tests/backend_consistency_tests")
set_tests_properties(BackendConsistencyTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;79;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(AutogradTests "/home/daniel/Projects/vesper/build-cpu/tests/autograd_tests")
set_tests_properties(AutogradTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;84;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(AutogradEngineTests "/home/daniel/Projects/vesper/build-cpu/tests/autograd_engine_tests")
set_tests_properties(AutogradEngineTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;89;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(AutogradReductionTests "/home/daniel/Projects/vesper/build-cpu/tests/autograd_reduction_tests")
set_tests_properties(AutogradReductionTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;94;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(AutogradMatmulTests "/home/daniel/Projects/vesper/build-cpu/tests/autograd_matmul_tests")
set_tests_properties(AutogradMatmulTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;99;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TensorViewTests "/home/daniel/Projects/vesper/build-cpu/tests/tensor_view_tests")
set_tests_properties(TensorViewTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;104;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(NnModuleTests "/home/daniel/Projects/vesper/build-cpu/tests/nn_module_tests")
set_tests_properties(NnModuleTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;109;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(NnLayerTests "/home/daniel/Projects/vesper/build-cpu/tests/nn_layer_tests")
set_tests_properties(NnLayerTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;114;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(AutogradOpsTests "/home/daniel/Projects/vesper/build-cpu/tests/autograd_ops_tests")
set_tests_properties(AutogradOpsTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;119;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(ActivationTests "/home/daniel/Projects/vesper/build-cpu/tests/activation_tests")
set_tests_properties(ActivationTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;124;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(NnComplexTests "/home/daniel/Projects/vesper/build-cpu/tests/nn_complex_tests")
set_tests_properties(NnComplexTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;129;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(LinearGradCheckTests "/home/daniel/Projects/vesper/build-cpu/tests/linear_grad_check_tests")
set_tests_properties(LinearGradCheckTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;134;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(AutogradMatmulComplexTests "/home/daniel/Projects/vesper/build-cpu/tests/autograd_matmul_complex_tests")
set_tests_properties(AutogradMatmulComplexTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;139;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(ActivationEdgeTests "/home/daniel/Projects/vesper/build-cpu/tests/activation_edge_tests")
set_tests_properties(ActivationEdgeTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;144;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(StressLargeTests "/home/daniel/Projects/vesper/build-cpu/tests/stress_large_tests")
set_tests_properties(StressLargeTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;149;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(BroadcastingHipTests "/home/daniel/Projects/vesper/build-cpu/tests/broadcasting_hip_tests")
set_tests_properties(BroadcastingHipTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;154;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(NnGpuTests "/home/daniel/Projects/vesper/build-cpu/tests/nn_gpu_tests")
set_tests_properties(NnGpuTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;159;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(DivMeanGpuTests "/home/daniel/Projects/vesper/build-cpu/tests/div_mean_gpu_tests")
set_tests_properties(DivMeanGpuTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;164;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(RandomGpuTests "/home/daniel/Projects/vesper/build-cpu/tests/random_gpu_tests")
set_tests_properties(RandomGpuTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;169;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(LossGpuTests "/home/daniel/Projects/vesper/build-cpu/tests/loss_gpu_tests")
set_tests_properties(LossGpuTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;174;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(OptimizerTests "/home/daniel/Projects/vesper/build-cpu/tests/optimizer_tests")
set_tests_properties(OptimizerTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;179;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(SgdTests "/home/daniel/Projects/vesper/build-cpu/tests/sgd_tests")
set_tests_properties(SgdTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;184;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TrainingLoopTests "/home/daniel/Projects/vesper/build-cpu/tests/training_loop_tests")
set_tests_properties(TrainingLoopTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;189;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(DataTests "/home/daniel/Projects/vesper/build-cpu/tests/data_tests")
set_tests_properties(DataTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;194;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(StackOpTests "/home/daniel/Projects/vesper/build-cpu/tests/stack_op_tests")
set_tests_properties(StackOpTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;199;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(AutogradMoreOpsTests "/home/daniel/Projects/vesper/build-cpu/tests/autograd_more_ops_tests")
set_tests_properties(AutogradMoreOpsTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;204;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TensorSlicingTests "/home/daniel/Projects/vesper/build-cpu/tests/tensor_slicing_tests")
set_tests_properties(TensorSlicingTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;209;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TensorIndexingTests "/home/daniel/Projects/vesper/build-cpu/tests/tensor_indexing_tests")
set_tests_properties(TensorIndexingTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;214;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(ViewTests "/home/daniel/Projects/vesper/build-cpu/tests/view_tests")
set_tests_properties(ViewTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;219;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(ViewAdvancedTests "/home/daniel/Projects/vesper/build-cpu/tests/view_advanced_tests")
set_tests_properties(ViewAdvancedTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;223;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(DataloaderShuffleTests "/home/daniel/Projects/vesper/build-cpu/tests/dataloader_shuffle_tests")
set_tests_properties(DataloaderShuffleTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;228;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(BroadcastingTests "/home/daniel/Projects/vesper/build-cpu/tests/broadcasting_tests")
set_tests_properties(BroadcastingTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;233;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(BroadcastingRigorousTests "/home/daniel/Projects/vesper/build-cpu/tests/broadcasting_rigorous_tests")
set_tests_properties(BroadcastingRigorousTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;237;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(ApiErgonomicsTests "/home/daniel/Projects/vesper/build-cpu/tests/api_ergonomics_tests")
set_tests_properties(ApiErgonomicsTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;241;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(Conv2dTests "/home/daniel/Projects/vesper/build-cpu/tests/conv2d_tests")
set_tests_properties(Conv2dTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;246;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(PoolingTests "/home/daniel/Projects/vesper/build-cpu/tests/pooling_tests")
set_tests_properties(PoolingTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;251;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(InplaceSafetyTests "/home/daniel/Projects/vesper/build-cpu/tests/inplace_safety_tests")
set_tests_properties(InplaceSafetyTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;256;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(InitTests "/home/daniel/Projects/vesper/build-cpu/tests/init_tests")
set_tests_properties(InitTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;261;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(OptimizerConvergenceTests "/home/daniel/Projects/vesper/build-cpu/tests/optimizer_convergence_tests")
set_tests_properties(OptimizerConvergenceTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;266;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(OptimizerRigorousTests "/home/daniel/Projects/vesper/build-cpu/tests/optimizer_rigorous_tests")
set_tests_properties(OptimizerRigorousTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;271;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(SchedulerTests "/home/daniel/Projects/vesper/build-cpu/tests/scheduler_tests")
set_tests_properties(SchedulerTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;276;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(SerializationTests "/home/daniel/Projects/vesper/build-cpu/tests/serialization_tests")
set_tests_properties(SerializationTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;281;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(SerializationRigorousTests "/home/daniel/Projects/vesper/build-cpu/tests/serialization_rigorous_tests")
set_tests_properties(SerializationRigorousTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;286;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(SerializationEdgeTests "/home/daniel/Projects/vesper/build-cpu/tests/serialization_edge_tests")
set_tests_properties(SerializationEdgeTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;291;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(EmbeddingTests "/home/daniel/Projects/vesper/build-cpu/tests/embedding_tests")
set_tests_properties(EmbeddingTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;296;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(MemoryLeakTests "/home/daniel/Projects/vesper/build-cpu/tests/memory_leak_tests")
set_tests_properties(MemoryLeakTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;301;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(ViewAutogradTests "/home/daniel/Projects/vesper/build-cpu/tests/view_autograd_tests")
set_tests_properties(ViewAutogradTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;306;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(CastTests "/home/daniel/Projects/vesper/build-cpu/tests/cast_tests")
set_tests_properties(CastTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;311;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(MoreOpsTests "/home/daniel/Projects/vesper/build-cpu/tests/more_ops_tests")
set_tests_properties(MoreOpsTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;316;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(NormalizationTests "/home/daniel/Projects/vesper/build-cpu/tests/normalization_tests")
set_tests_properties(NormalizationTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;321;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(SoftmaxTests "/home/daniel/Projects/vesper/build-cpu/tests/softmax_tests")
set_tests_properties(SoftmaxTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;326;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(BatchGemmTests "/home/daniel/Projects/vesper/build-cpu/tests/batch_gemm_tests")
set_tests_properties(BatchGemmTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;331;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(BatchGemmComprehensiveTests "/home/daniel/Projects/vesper/build-cpu/tests/batch_gemm_comprehensive_tests")
set_tests_properties(BatchGemmComprehensiveTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;336;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(AttentionTests "/home/daniel/Projects/vesper/build-cpu/tests/attention_tests")
set_tests_properties(AttentionTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;341;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(sum_dim_tests "/home/daniel/Projects/vesper/build-cpu/tests/sum_dim_tests")
set_tests_properties(sum_dim_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;345;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(DropoutTests "/home/daniel/Projects/vesper/build-cpu/tests/dropout_tests")
set_tests_properties(DropoutTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;350;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(RobustnessTests "/home/daniel/Projects/vesper/build-cpu/tests/robustness_tests")
set_tests_properties(RobustnessTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;355;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TransformerTests "/home/daniel/Projects/vesper/build-cpu/tests/transformer_tests")
set_tests_properties(TransformerTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;360;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(LinearRegressionLargeTests "/home/daniel/Projects/vesper/build-cpu/tests/linear_regression_large_tests")
set_tests_properties(LinearRegressionLargeTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;365;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(StressTrainingTests "/home/daniel/Projects/vesper/build-cpu/tests/stress_training_tests")
set_tests_properties(StressTrainingTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;375;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(RopeTests "/home/daniel/Projects/vesper/build-cpu/tests/rope_tests")
set_tests_properties(RopeTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;380;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(KVCacheTests "/home/daniel/Projects/vesper/build-cpu/tests/kv_cache_tests")
set_tests_properties(KVCacheTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;385;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TransformerBlockTests "/home/daniel/Projects/vesper/build-cpu/tests/transformer_block_tests")
set_tests_properties(TransformerBlockTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;390;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(NormalizationGradTests "/home/daniel/Projects/vesper/build-cpu/tests/normalization_grad_tests")
set_tests_properties(NormalizationGradTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;395;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(NormalizationIntegrationTests "/home/daniel/Projects/vesper/build-cpu/tests/normalization_integration_tests")
set_tests_properties(NormalizationIntegrationTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;400;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(SoftmaxComprehensiveTests "/home/daniel/Projects/vesper/build-cpu/tests/softmax_comprehensive_tests")
set_tests_properties(SoftmaxComprehensiveTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;405;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(AttentionComprehensiveTests "/home/daniel/Projects/vesper/build-cpu/tests/attention_comprehensive_tests")
set_tests_properties(AttentionComprehensiveTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;410;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TransformerComponentsTests "/home/daniel/Projects/vesper/build-cpu/tests/transformer_components_tests")
set_tests_properties(TransformerComponentsTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;415;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(BatchGemmEdgeTests "/home/daniel/Projects/vesper/build-cpu/tests/batch_gemm_edge_tests")
set_tests_properties(BatchGemmEdgeTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;420;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(AttentionChapter32Tests "/home/daniel/Projects/vesper/build-cpu/tests/attention_chapter32_tests")
set_tests_properties(AttentionChapter32Tests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;425;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TransformerBlockChapter33Tests "/home/daniel/Projects/vesper/build-cpu/tests/transformer_block_chapter33_tests")
set_tests_properties(TransformerBlockChapter33Tests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;430;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(KVCacheChapter33Tests "/home/daniel/Projects/vesper/build-cpu/tests/kv_cache_chapter33_tests")
set_tests_properties(KVCacheChapter33Tests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;435;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(RoPEChapter33Tests "/home/daniel/Projects/vesper/build-cpu/tests/rope_chapter33_tests")
set_tests_properties(RoPEChapter33Tests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;440;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(SwiGLUChapter33Tests "/home/daniel/Projects/vesper/build-cpu/tests/swiglu_chapter33_tests")
set_tests_properties(SwiGLUChapter33Tests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;445;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(InplaceToTests "/home/daniel/Projects/vesper/build-cpu/tests/inplace_to_tests")
set_tests_properties(InplaceToTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;450;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(ModuleListTests "/home/daniel/Projects/vesper/build-cpu/tests/module_list_tests")
set_tests_properties(ModuleListTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;455;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(GQAChapter33Tests "/home/daniel/Projects/vesper/build-cpu/tests/gqa_chapter33_tests")
set_tests_properties(GQAChapter33Tests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;460;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TransformerModelChapter33Tests "/home/daniel/Projects/vesper/build-cpu/tests/transformer_model_chapter33_tests")
set_tests_properties(TransformerModelChapter33Tests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;465;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(GenerationChapter33Tests "/home/daniel/Projects/vesper/build-cpu/tests/generation_chapter33_tests")
set_tests_properties(GenerationChapter33Tests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;470;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(SafetensorsTests "/home/daniel/Projects/vesper/build-cpu/tests/safetensors_tests")
set_tests_properties(SafetensorsTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;475;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(HalfPrecisionTests "/home/daniel/Projects/vesper/build-cpu/tests/half_precision_tests")
set_tests_properties(HalfPrecisionTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;480;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(FlashAttentionTests "/home/daniel/Projects/vesper/build-cpu/tests/flash_attention_tests")
set_tests_properties(FlashAttentionTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;485;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(GradientCheckpointingTests "/home/daniel/Projects/vesper/build-cpu/tests/gradient_checkpointing_tests")
set_tests_properties(GradientCheckpointingTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;490;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(MemoryEfficientTrainingTests "/home/daniel/Projects/vesper/build-cpu/tests/memory_efficient_training_tests")
set_tests_properties(MemoryEfficientTrainingTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;495;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(IndexOpsTests "/home/daniel/Projects/vesper/build-cpu/tests/index_ops_tests")
set_tests_properties(IndexOpsTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;500;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(FusedOpsTests "/home/daniel/Projects/vesper/build-cpu/tests/fused_ops_tests")
set_tests_properties(FusedOpsTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;505;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(FP16GemmTests "/home/daniel/Projects/vesper/build-cpu/tests/fp16_gemm_tests")
set_tests_properties(FP16GemmTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;510;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(TrainingStabilityTests "/home/daniel/Projects/vesper/build-cpu/tests/training_stability_tests")
set_tests_properties(TrainingStabilityTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;515;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(CatOpTests "/home/daniel/Projects/vesper/build-cpu/tests/cat_op_tests")
set_tests_properties(CatOpTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;520;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(ReductionTieGradTests "/home/daniel/Projects/vesper/build-cpu/tests/reduction_tie_grad_tests")
set_tests_properties(ReductionTieGradTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;525;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(PrefetchDataLoaderTests "/home/daniel/Projects/vesper/build-cpu/tests/prefetch_dataloader_tests")
set_tests_properties(PrefetchDataLoaderTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;530;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
add_test(CrossEntropyIgnoreIndexTests "/home/daniel/Projects/vesper/build-cpu/tests/cross_entropy_ignore_index_tests")
set_tests_properties(CrossEntropyIgnoreIndexTests PROPERTIES  _BACKTRACE_TRIPLES "/home/daniel/Projects/vesper/tests/CMakeLists.txt;535;add_test;/home/daniel/Projects/vesper/tests/CMakeLists.txt;0;")
